version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/config/Dockerfile
      args:
        - MEDIA_URL=${MEDIA_URL}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - SENTRY_WEB_DSN=${SENTRY_WEB_DSN}
    restart: always
    ports:
      - 3001:3001
    env_file:
      - .env
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/config/Dockerfile
    restart: always
    ports:
      - 9001:9001
