name: prod-api-deploy

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: api-prod

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: npm install --force
      - name: Delete pm2 api
        working-directory: apps/api
        run: pm2 delete api
        continue-on-error: true
      - name: Start pm2 api
        working-directory: apps/api
        run: pm2 start npm --name api -- run dev
      - name: Show pm2 api
        working-directory: apps/api
        run: pm2 describe api
      - name: Show pm2 api logs
        working-directory: apps/api
        run: pm2 logs --nostream
